//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.23 at 04:41:58 PM CET 
//


package org.s23m.cell.serialization;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for instantiationSemantic.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="instantiationSemantic">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="InstantiatedAbstractArtifact"/>
 *     &lt;enumeration value="InstantiatedConcreteArtifact"/>
 *     &lt;enumeration value="InstantiateSemanticDomain"/>
 *     &lt;enumeration value="SemanticDomainAddition"/>
 *     &lt;enumeration value="DisjunctSemanticIdentitySetAddition"/>
 *     &lt;enumeration value="AnonDisjunctSemanticIdentitySetAddition"/>
 *     &lt;enumeration value="SemanticRoleAddition"/>
 *     &lt;enumeration value="AnonSemanticRoleAddition"/>
 *     &lt;enumeration value="AbstractVertex"/>
 *     &lt;enumeration value="ConcreteVertex"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum InstantiationSemantic {

    @XmlEnumValue("AbstractVertex")
    ABSTRACT_VERTEX("AbstractVertex"),
    @XmlEnumValue("AnonDisjunctSemanticIdentitySetAddition")
    ANON_DISJUNCT_SEMANTIC_IDENTITY_SET_ADDITION("AnonDisjunctSemanticIdentitySetAddition"),
    @XmlEnumValue("AnonSemanticRoleAddition")
    ANON_SEMANTIC_ROLE_ADDITION("AnonSemanticRoleAddition"),
    @XmlEnumValue("ConcreteVertex")
    CONCRETE_VERTEX("ConcreteVertex"),
    @XmlEnumValue("DisjunctSemanticIdentitySetAddition")
    DISJUNCT_SEMANTIC_IDENTITY_SET_ADDITION("DisjunctSemanticIdentitySetAddition"),
    @XmlEnumValue("InstantiatedAbstractArtifact")
    INSTANTIATED_ABSTRACT_ARTIFACT("InstantiatedAbstractArtifact"),
    @XmlEnumValue("InstantiatedConcreteArtifact")
    INSTANTIATED_CONCRETE_ARTIFACT("InstantiatedConcreteArtifact"),
    @XmlEnumValue("InstantiateSemanticDomain")
    INSTANTIATE_SEMANTIC_DOMAIN("InstantiateSemanticDomain"),
    @XmlEnumValue("SemanticDomainAddition")
    SEMANTIC_DOMAIN_ADDITION("SemanticDomainAddition"),
    @XmlEnumValue("SemanticRoleAddition")
    SEMANTIC_ROLE_ADDITION("SemanticRoleAddition");
    private final String value;

    InstantiationSemantic(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InstantiationSemantic fromValue(String v) {
        for (InstantiationSemantic c: InstantiationSemantic.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
