//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.23 at 04:41:58 PM CET 
//


package org.s23m.cell.serialization;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for linkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="linkType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="visibility" type="{http://schemas.gmodel.org/serialization/2010}visibilityType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="edge" type="{http://schemas.gmodel.org/serialization/2010}edgeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="edgeTrace" type="{http://schemas.gmodel.org/serialization/2010}edgeTraceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="superSetReference" type="{http://schemas.gmodel.org/serialization/2010}superSetReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "linkType", propOrder = {
    "visibilityAndEdgeAndEdgeTrace"
})
public class LinkType {

    @XmlElements({
        @XmlElement(name = "edgeTrace", namespace = "http://schemas.gmodel.org/serialization/2010", required = true, type = EdgeTraceType.class),
        @XmlElement(name = "edge", namespace = "http://schemas.gmodel.org/serialization/2010", required = true, type = EdgeType.class),
        @XmlElement(name = "visibility", namespace = "http://schemas.gmodel.org/serialization/2010", required = true, type = VisibilityType.class),
        @XmlElement(name = "superSetReference", namespace = "http://schemas.gmodel.org/serialization/2010", required = true, type = SuperSetReferenceType.class)
    })
    protected List<Object> visibilityAndEdgeAndEdgeTrace;

    /**
     * Gets the value of the visibilityAndEdgeAndEdgeTrace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visibilityAndEdgeAndEdgeTrace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisibilityAndEdgeAndEdgeTrace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EdgeTraceType }
     * {@link EdgeType }
     * {@link VisibilityType }
     * {@link SuperSetReferenceType }
     * 
     * 
     */
    public List<Object> getVisibilityAndEdgeAndEdgeTrace() {
        if (visibilityAndEdgeAndEdgeTrace == null) {
            visibilityAndEdgeAndEdgeTrace = new ArrayList<Object>();
        }
        return this.visibilityAndEdgeAndEdgeTrace;
    }

}
