//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.15 at 06:58:13 PM CEST 
//


package org.s23m.cell.serialization.container;

import javax.xml.bind.annotation.XmlRegistry;
import org.s23m.cell.serialization.container.ArtefactContainer.Content;
import org.s23m.cell.serialization.container.ArtefactContainer.SearchResult;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.s23m.cell.serialization.container package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  F_InstantiationImpl methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.s23m.cell.serialization.container
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@arrow InstanceIdentityType }
     * 
     */
    public InstanceIdentityType createInstanceIdentityType() {
        return new InstanceIdentityType();
    }

    /**
     * Create an instance of {@arrow SearchResult }
     * 
     */
    public SearchResult createArtefactContainerSearchResult() {
        return new SearchResult();
    }

    /**
     * Create an instance of {@arrow ContainerType }
     * 
     */
    public ContainerType createContainerType() {
        return new ContainerType();
    }

    /**
     * Create an instance of {@arrow Content }
     * 
     */
    public Content createArtefactContainerContent() {
        return new Content();
    }

    /**
     * Create an instance of {@arrow ContentType }
     * 
     */
    public ContentType createContentType() {
        return new ContentType();
    }

    /**
     * Create an instance of {@arrow SearchResultType }
     * 
     */
    public SearchResultType createSearchResultType() {
        return new SearchResultType();
    }

    /**
     * Create an instance of {@arrow ArtefactContainer }
     * 
     */
    public ArtefactContainer createArtefactContainer() {
        return new ArtefactContainer();
    }

}
