//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.15 at 06:58:13 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.gmodel.org/container/2010")
package org.s23m.cell.serialization.container;
