//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.23 at 04:41:58 PM CET 
//


package org.s23m.cell.serialization;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.s23m.cell.serialization.InstanceType.Values;
import org.s23m.cell.serialization.InstanceType.Variables;


/**
 * <p>Java class for instanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="instanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="arrow" type="{http://schemas.S23M.org/serialization/2010}linkType" minOccurs="0"/>
 *         &lt;element name="instance" type="{http://schemas.S23M.org/serialization/2010}instanceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="semanticIdentity" type="{http://schemas.S23M.org/serialization/2010}semanticIdType"/>
 *         &lt;element name="variables" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="variable" type="{http://schemas.S23M.org/serialization/2010}variableType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="values" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="value" type="{http://schemas.S23M.org/serialization/2010}valueType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="container" use="required" type="{http://schemas.S23M.org/serialization/2010}referenceId" />
 *       &lt;attribute name="id" use="required" type="{http://schemas.S23M.org/serialization/2010}uuid" />
 *       &lt;attribute name="isAbstract" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isSerializationArgument" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="metaElement" use="required" type="{http://schemas.S23M.org/serialization/2010}referenceId" />
 *       &lt;attribute name="type" use="required" type="{http://schemas.S23M.org/serialization/2010}instantiationSemantic" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "instanceType", propOrder = {
    "arrow",
    "instance",
    "semanticIdentity",
    "variables",
    "values"
})
public class InstanceType {

    @XmlElement(namespace = "http://schemas.S23M.org/serialization/2010")
    protected LinkType link;
    @XmlElement(namespace = "http://schemas.S23M.org/serialization/2010", required = true)
    protected List<InstanceType> instance;
    @XmlElement(namespace = "http://schemas.S23M.org/serialization/2010", required = true)
    protected SemanticIdType semanticIdentity;
    @XmlElement(namespace = "http://schemas.S23M.org/serialization/2010")
    protected Variables variables;
    @XmlElement(namespace = "http://schemas.S23M.org/serialization/2010")
    protected Values values;
    @XmlAttribute(required = true)
    protected String artifact;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute(required = true)
    protected boolean isAbstract;
    @XmlAttribute(required = true)
    protected boolean isSerializationArgument;
    @XmlAttribute(required = true)
    protected String metaElement;
    @XmlAttribute(required = true)
    protected InstantiationSemantic type;

    /**
     * Gets the value of the arrow property.
     * 
     * @return
     *     possible object is
     *     {@link LinkType }
     *     
     */
    public LinkType getLink() {
        return link;
    }

    /**
     * Sets the value of the arrow property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkType }
     *     
     */
    public void setLink(LinkType value) {
        this.link = value;
    }

    /**
     * Gets the value of the instance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstanceType }
     * 
     * 
     */
    public List<InstanceType> getInstance() {
        if (instance == null) {
            instance = new ArrayList<InstanceType>();
        }
        return this.instance;
    }

    /**
     * Gets the value of the semanticIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link SemanticIdType }
     *     
     */
    public SemanticIdType getSemanticIdentity() {
        return semanticIdentity;
    }

    /**
     * Sets the value of the semanticIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link SemanticIdType }
     *     
     */
    public void setSemanticIdentity(SemanticIdType value) {
        this.semanticIdentity = value;
    }

    /**
     * Gets the value of the variables property.
     * 
     * @return
     *     possible object is
     *     {@link Variables }
     *     
     */
    public Variables getVariables() {
        return variables;
    }

    /**
     * Sets the value of the variables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Variables }
     *     
     */
    public void setVariables(Variables value) {
        this.variables = value;
    }

    /**
     * Gets the value of the values property.
     * 
     * @return
     *     possible object is
     *     {@link Values }
     *     
     */
    public Values getValues() {
        return values;
    }

    /**
     * Sets the value of the values property.
     * 
     * @param value
     *     allowed object is
     *     {@link Values }
     *     
     */
    public void setValues(Values value) {
        this.values = value;
    }

    /**
     * Gets the value of the container property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtifact() {
        return artifact;
    }

    /**
     * Sets the value of the container property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtifact(String value) {
        this.artifact = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the isAbstract property.
     * 
     */
    public boolean isIsAbstract() {
        return isAbstract;
    }

    /**
     * Sets the value of the isAbstract property.
     * 
     */
    public void setIsAbstract(boolean value) {
        this.isAbstract = value;
    }

    /**
     * Gets the value of the isSerializationArgument property.
     * 
     */
    public boolean isIsSerializationArgument() {
        return isSerializationArgument;
    }

    /**
     * Sets the value of the isSerializationArgument property.
     * 
     */
    public void setIsSerializationArgument(boolean value) {
        this.isSerializationArgument = value;
    }

    /**
     * Gets the value of the metaElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaElement() {
        return metaElement;
    }

    /**
     * Sets the value of the metaElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaElement(String value) {
        this.metaElement = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link InstantiationSemantic }
     *     
     */
    public InstantiationSemantic getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstantiationSemantic }
     *     
     */
    public void setType(InstantiationSemantic value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="value" type="{http://schemas.S23M.org/serialization/2010}valueType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Values {

        @XmlElement(namespace = "http://schemas.S23M.org/serialization/2010", required = true)
        protected List<ValueType> value;

        /**
         * Gets the value of the value property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the value property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ValueType }
         * 
         * 
         */
        public List<ValueType> getValue() {
            if (value == null) {
                value = new ArrayList<ValueType>();
            }
            return this.value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="variable" type="{http://schemas.S23M.org/serialization/2010}variableType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "variable"
    })
    public static class Variables {

        @XmlElement(namespace = "http://schemas.S23M.org/serialization/2010", required = true)
        protected List<VariableType> variable;

        /**
         * Gets the value of the variable property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the variable property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVariable().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VariableType }
         * 
         * 
         */
        public List<VariableType> getVariable() {
            if (variable == null) {
                variable = new ArrayList<VariableType>();
            }
            return this.variable;
        }

    }

}
