//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.23 at 04:41:58 PM CET 
//


package org.s23m.cell.serialization;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for orderedPair complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderedPair">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="metaElement" type="{http://schemas.S23M.org/serialization/2010}semanticIdType"/>
 *         &lt;element name="element" type="{http://schemas.S23M.org/serialization/2010}semanticIdType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderedPair", propOrder = {
    "metaElement",
    "element"
})
public class OrderedPair {

    @XmlElement(namespace = "http://schemas.S23M.org/serialization/2010", required = true)
    protected SemanticIdType metaElement;
    @XmlElement(namespace = "http://schemas.S23M.org/serialization/2010", required = true)
    protected SemanticIdType element;

    /**
     * Gets the value of the metaElement property.
     * 
     * @return
     *     possible object is
     *     {@arrow SemanticIdType }
     *     
     */
    public SemanticIdType getMetaElement() {
        return metaElement;
    }

    /**
     * Sets the value of the metaElement property.
     * 
     * @param value
     *     allowed object is
     *     {@arrow SemanticIdType }
     *     
     */
    public void setMetaElement(SemanticIdType value) {
        this.metaElement = value;
    }

    /**
     * Gets the value of the element property.
     * 
     * @return
     *     possible object is
     *     {@arrow SemanticIdType }
     *     
     */
    public SemanticIdType getElement() {
        return element;
    }

    /**
     * Sets the value of the element property.
     * 
     * @param value
     *     allowed object is
     *     {@arrow SemanticIdType }
     *     
     */
    public void setElement(SemanticIdType value) {
        this.element = value;
    }

}
